
const Shoesdata = [

    { id:1000081, shoesname: 'Nike Pegasus 39',color:'Grey', price:'10495', cover:'https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/705c072d-0c30-49b3-81ce-42e95b118e31/pegasus-39-road-running-shoes-kmZSD6.png',description:'Let the Nike Pegasus 39 help you ascend to new heights. More lightweight up top than the Pegasus 38 and ideal to wear in any season, it has a supportive sensation to help keep your feet contained, while underfoot cushioning and double Zoom Air units (1 more than the Peg 38) give you an extra pop to your step. Your trusted workhorse with wings is back. Time to fly.' },
    { id:1000082, shoesname: 'Nike Free Metcon 4',color:'Black', price:'10295', cover:'https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/3954af94-ef0e-4277-a3a2-2df84eba652a/free-metcon-4-training-shoes-hr4JbW.png',description:'The Nike Free Metcon 4 combines flexibility with stability to help you get the most out of your training programme. Updated "chain-link" mesh cools and flexes as you speed through agility drills, while support at the midfoot and heel braces you for your heaviest sets in the weight room.'  },
    { id:1000083, shoesname: 'Nike Air Zoom G.T. Jump',color:'Orange', price:'16595', cover:'https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/5c3654f1-e3d9-4d9d-838e-fe4cdc30d352/air-zoom-gt-jump-basketball-shoes-22QS5F.png',description:'Feel like defying gravity? Meet one of Nike Basketballs most responsive cushioning systems ever devised for game shoes. The double-stacked Zoom Air works in unison with an external jump frame made from PEBAX® thats lightweight, springy and strong. The woven exoskeleton-like upper helps you feel fully connected, so you can move with confidence and power and defeat the force that holds you down.'  },
    { id:1000084, shoesname: 'Nike Phantom GT2 Dynamic',color:'White', price:'20897', cover:'https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/c15664d4-f628-4987-b9ad-9fdffaabfa83/phantom-gt2-dynamic-fit-elite-fg-football-boots-c2H8s5.png',description:'Building off the Phantom GT, the Nike Phantom GT2 Elite FG features an updated design and raised patterning to help create optimal spin to control the flight of the ball. Off-centre lacing provides a clean strike zone for skilful dribbling, passing and shooting.'  },
    { id:1000085, shoesname: 'Nike Free Run 5.0', price:'7047',color:'White', cover:'https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/ce27aca7-c615-43dc-aa9a-e7e96d8273fa/free-run-5-road-running-shoes-m8L9mr.png',description:'Made from at least 20% recycled material by weight, the sock-like boot of this Nike Free is designed to transition from running to training to your everyday routine. With a breathable knit upper, it combines the flexibility you love with a secure design that will help keep you close to the ground for that barefoot feeling. New cushioning is lighter, softer and more responsive than previous versions so you can keep moving in comfort whether youre on the tarmac or track.'  },
    { id:1000086, shoesname: 'Air Jordan 1 Retro High',color:'Bhue-Gray', price:'16995', cover:'https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/b1d3cf2e-0dca-4f6d-97ff-21006c346e8e/air-jordan-1-retro-high-og-shoes-Pz6fZ9.png',description:'3 + 1 = a whole new icon. Celebrating 35 years of the Air Jordan 3, these kicks combine the classic AJ1 silhouette with an original AJ3 colourway. Crafted to the 85 specs its got premium leather, a high-top collar and the woven tongue label you know and love. Bold splashes of True Blue throughout (check out the Wings logo) stand out against layers of white and Cement Grey. And the finishing touch? Nike Air cushioning underfoot lets you keep pace, so nothing holds you back from stepping out in style.'  },
    { id:1000087, shoesname: 'Nike Pegasus FlyEase', price:'10890',color:'Green', cover:'https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/e7a5ba73-4df3-4067-b49f-29b54bb07ca1/pegasus-flyease-easy-on-off-road-running-shoes-RlnnC7.png',description:'Let the Nike Pegasus FlyEase, a balanced and energised ride for any run, help you ascend to new heights. A supportive sensation helps keep your foot contained, while underfoot Air adds a pop to your step as you transition from heel to toe. Nike FlyEase technology acts as a strap, helping secure the fit. Your trusted workhorse with wings is back. Time to fly.'  },
    { id:1000088, shoesname: 'Nike City Rep TR', price:'4995',color:'Grey', cover:'https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/6a89d86c-673c-47d1-bab1-8792f907625b/city-rep-tr-training-shoes-djC0DF.png',description:'The Nike City Rep TR is a versatile shoe that brings durability and flexibility to your active urban lifestyle. Rubber tread gives you grip on a range of surfaces, while foam cushioning keeps your foot comfortable—during outdoor workouts and through the rest of your day.'  },
    { id:1000089, shoesname: 'Nike React Infinity 3',color:'Black', price:'13995', cover:'https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/a65c6560-0465-442c-b95a-5b924bd0a211/react-infinity-3-road-running-shoes-S5Srkq.png',description:'Still 1 of our most tested shoes, the Nike React Infinity 3 has soft and supportive cushioning. Its soft, stable feel with a smooth ride will carry you through routes, long and short. A breathable upper is made to feel contained, yet flexible. We even added more cushioning around the heel and ankle for a supportive sensation. Keep running—weve got you.'  }
    
    
    
    ]
    
    export default Shoesdata 

